# Linear algebra in Python with NumPy

In this lab, you will have the opportunity to remember some basic concepts about linear algebra and how to use them in Python.

Numpy is one of the most used libraries in Python for arrays manipulation. It adds to Python a set of functions that allows us to operate on large multidimensional arrays with just a few lines. So forget about writing nested loops for adding matrices! With NumPy, this is as simple as adding numbers.

Let us import the `numpy` library and assign the alias `np` for it. We will follow this convention in almost every notebook in this course, and you'll see this in many resources outside this course as well.

In [1]:
# importing numpy library

import numpy as np

In [3]:
# defining list and numpy array

alist = [1,2,3,4,5]
narray = np.array([1,2,3,4,5])

In [4]:
# printing values and type of both list and array

print(alist)
print(type(alist))

print(narray)
print(type(narray))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


## Algebraic operators on NumPy arrays vs. Python lists

One of the common beginner mistakes is to mix up the concepts of NumPy arrays and Python lists. Just observe the next example, where we add two objects of the two mentioned types. Note that the '+' operator on NumPy arrays perform an element-wise addition, while the same operation on Python lists results in a list concatenation. Be careful while coding. Knowing this can save many headaches.

In [5]:
# + operation on numpy array

print(narray + narray)

# + operation on python list

print(alist + alist)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


It is the same as with the product operator, `*`. In the first case, we scale the vector, while in the second case, we concatenate three times the same list.

In [6]:
# * operation on numpy array

print(narray * 2)

# * operation on python list

print(alist * 2)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Matrix or Array of Arrays

In linear algebra, a matrix is a structure composed of n rows by m columns. That means each row must have the same number of columns. With NumPy, we have two ways to create a matrix:
* Creating an array of arrays using `np.array` (recommended). 
* Creating a matrix using `np.matrix` (still available but might be removed soon).

NumPy arrays or lists can be used to initialize a matrix, but the resulting matrix will be composed of NumPy arrays only.

In [10]:
npmatrix1 = np.array([narray,narray,narray])
npmatrix2 = np.array([alist,alist,alist])
npmatrix3 = np.array([narray,[1,1,1,1,1],narray])

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 1 1 1 1]
 [1 2 3 4 5]]


In [12]:
# example 1

okmatrix = np.array([[1,2],[3,4]])
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [14]:
# example 2 

import warnings
warnings.filterwarnings("ignore")

badmatrix = np.array([[1,2],[3,4],[1,2,3]])
print(badmatrix)
print(badmatrix * 2)

[list([1, 2]) list([3, 4]) list([1, 2, 3])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([1, 2, 3, 1, 2, 3])]


## Scaling and translating matrices

Now that you know how to build correct NumPy arrays and matrices, let us see how easy it is to operate with them in Python using the regular algebraic operators like + and -. 

Operations can be performed between arrays and arrays or between arrays and scalars.

In [15]:
# scaling by 2 and translate 1 unit

result = okmatrix * 2 + 1
print(result)

[[3 5]
 [7 9]]


In [16]:
# addition 

result1 = okmatrix + okmatrix
print(result1)

# subtraction

result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


The product operator `*` when used on arrays or matrices indicates element-wise multiplications.
Do not confuse it with the dot product.

In [17]:
result = okmatrix * okmatrix
print(result)

[[ 1  4]
 [ 9 16]]


## Transpose a matrix

In linear algebra, the transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., the transpose operator switches the row and column indices of the matrix producing another matrix. If the original matrix dimension is n by m, the resulting transposed matrix will be m by n.

**T** denotes the transpose operations with NumPy matrices.

In [18]:
tmatrix = np.array([[1,2],[3,4],[5,6]])

print('---Before transpose---')
print(tmatrix)
print('---After transpose---')
print(tmatrix.T)

---Before transpose---
[[1 2]
 [3 4]
 [5 6]]
---After transpose---
[[1 3 5]
 [2 4 6]]


However, note that the transpose operation does not affect 1D arrays.

In [19]:
tmatrix = np.array([1,2,3,4])

print('---Before transpose---')
print(tmatrix)
print('---After transpose---')
print(tmatrix.T)

---Before transpose---
[1 2 3 4]
---After transpose---
[1 2 3 4]


In [20]:
tmatrix = np.array([[1,2,3,4]])

print('---Before transpose---')
print(tmatrix)
print('---After transpose---')
print(tmatrix.T)

---Before transpose---
[[1 2 3 4]]
---After transpose---
[[1]
 [2]
 [3]
 [4]]


## Get the norm of a nparray or matrix

In linear algebra, the norm of an n-dimensional vector $\vec a$   is defined as:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

Calculating the norm of vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linalg**, including the **norm** function. Let us see how to get the norm a given array or matrix:

In [22]:
narray1 = np.array([1,2,3,4])
narray1 = np.linalg.norm(narray1)

narray2 = np.array([[1,2],[3,4]])
narray2 = np.linalg.norm(narray2)

print(narray1)
print(narray2)

5.477225575051661
5.477225575051661


Note that without any other parameter, the norm function treats the matrix as being just an array of numbers.
However, it is possible to get the norm by rows or by columns. The **axis** parameter controls the form of the operation: 
* **axis=0** means get the norm of each column
* **axis=1** means get the norm of each row. 

In [39]:
narray = np.array([[1,1],[2,2],[3,3]])

narray_col = np.linalg.norm(narray,axis = 0)
narray_row = np.linalg.norm(narray,axis = 1)

print(narray_col)
print(narray_row)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


## The dot product between arrays: All the flavors

The dot product or scalar product or inner product between two vectors $\vec a$ and $\vec b$ of the same size is defined as:
$$\vec a \cdot \vec b = \sum_{i=1}^{n} a_i b_i$$

The dot product takes two vectors and returns a single number.

In [26]:
narray1 = np.array([1,2,3,4])
narray2 = np.array([5,6,7,8])

way1 = np.dot(narray1,narray2)
print(way1)

way2 = np.sum(narray1 * narray2)
print(way2)

way3 = narray1 @ narray2
print(way3)

way4 = 0
for a,b in zip(narray1,narray2):
    way4 += a*b
    
print(way4)

70
70
70
70


**benefit of using np.dot, since it is the only method that accepts arrays and lists without problems**

In [27]:
narray1 = np.dot(np.array([1,2]),np.array([3,4]))
narray2 = np.dot([1,2],[3,4])

print(narray1,"=",narray2)

11 = 11


Finally, note that the norm is the square root of the dot product of the vector with itself. That gives many options to write that function:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2} = \sqrt {a \cdot a}$$


## Sums by rows or columns

Another general operation performed on matrices is the sum by rows or columns.
Just as we did for the function norm, the **axis** parameter controls the form of the operation:
* **axis=0** means to sum the elements of each column together. 
* **axis=1** means to sum the elements of each row together.

In [42]:
narray1 = np.array([[1,2],[4,5],[6,7]])
narray1

array([[1, 2],
       [4, 5],
       [6, 7]])

In [44]:
sumBycol = np.sum(narray1,axis=0)
sumByrow = np.sum(narray1,axis=1)
print(sumBycol)
print(sumByrow)

[11 14]
[ 3  9 13]


## Get the mean by rows or columns

As with the sums, one can get the **mean** by rows or columns using the **axis** parameter. Just remember that the mean is the sum of the elements divided by the length of the vector
$$ mean(\vec a) = \frac {{\sum_{i=1}^{n} a_i }}{n}$$

In [46]:
narray = np.array([[1,2],[3,4],[5,6]])

mean = np.mean(narray)
meanBycol = np.mean(narray,axis = 0)
meanByrow = np.mean(narray,axis = 1)

print('Array Matrix',narray)
print('mean',mean)
print('Mean by column',meanBycol)
print('Mean by row',meanByrow)

Array Matrix [[1 2]
 [3 4]
 [5 6]]
mean 3.5
Mean by column [3. 4.]
Mean by row [1.5 3.5 5.5]


## Center the columns of a matrix

Centering the attributes of a data matrix is another essential preprocessing step. Centering a matrix means to remove the column mean to each element inside the column. The sum by columns of a centered matrix is always 0.

With NumPy, this process is as simple as this:

In [48]:
narray = np.array([[1,2],[3,4],[5,6]])

narrayCentered = narray - np.mean(narray,axis = 0) # remove mean from each column

print("--Original Matrix--")
print(narray)

print("--Centered Matrix--")
print(narrayCentered)

print('New mean by column')
print(narrayCentered.mean(axis=0))

--Original Matrix--
[[1 2]
 [3 4]
 [5 6]]
--Centered Matrix--
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
New mean by column
[0. 0.]


**Warning:** This process does not apply for row centering. In such cases, consider transposing the matrix, centering by columns, and then transpose back the result. 

See the example below:

In [49]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


Note that some operations can be performed using static functions like `np.sum()` or `np.mean()`, or by using the inner functions of the array

In [51]:
narray = np.array([[1,2],[3,4]])

print(np.mean(narray))
print(narray.mean())

2.5
2.5


**Even if they are equivalent,recommend is static way always.**