# Introduction to Numpy

In [1]:
# importing library

import numpy as np

In [2]:
# creating numpy array

lst = [[1,2,3],[4,5,6]]
twod_array = np.array(lst)
twod_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# checking array datatype

twod_array.dtype

dtype('int64')

In [4]:
# let's convert this to another dtype other than 64 bit

twod_array.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [5]:
# let's convert this to another data type say float

twod_array.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
# Checking dimensions

twod_array.ndim

2

In [7]:
# checking shape

twod_array.shape

(2, 3)

## Numpy array construction and indexing

In [8]:
# creating array of ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# with other data type by default it's in float

np.ones((3,3),dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
# creating array of zeros

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# to get help about any function

# way 1

np.ones?

# way 2

help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

Signature: np.ones(shape, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
    

In [12]:
# adding values to np array

np.ones((3,3)) + 99

array([[100., 100., 100.],
       [100., 100., 100.],
       [100., 100., 100.]])

In [13]:
# creating empty array
# it will assign any random values while creating array

np.empty((2,3))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
# for identity matrix we use eye matrix

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# to create diagonal matrix

np.diag((3,3,3))

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [18]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
# arange function create numpy array with starting and ending value exclusive upper limit

np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [20]:
# if we use one value then it will consider the value as stopping value

np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [21]:
# let's introduce stepping values
# skipping even values

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
# we can introduce very small interval

np.arange(1.,10.,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [23]:
# linspace function will generate numpy array related to numbers provided.
# for example if we want to generate 5 numbers then it will select the interval accordingly.
# created 10 numbers numpy array with interval defined according to total numbers required.

np.linspace(1.,4.,num = 10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

## Numpy Array Indexing
1D numpy array indexing works similar like python list indexing

In [26]:
# using index value

arr = np.array([1,2,3])
arr[0]

1

In [27]:
# slicing

arr[:2]

array([1, 2])

In [29]:
# 2-D indexing

arr2D = np.array([[1,2,3],
                 [4,5,6]])

In [32]:
# first value is for row and 2nd value is for column

print(arr2D[0,0])
print(arr2D[1,1])

1
5


In [33]:
# reverse indexing

arr2D[0,-1]

3

In [34]:
# to get entire row we can omit 2nd parameter value

arr2D[0]

array([1, 2, 3])

## Numpy array math and universal function

In [36]:
# Addition operation.
# Adding 1 to each element of the numpy array.
# this method is also called binary ufunc as it takes two arguments.

arr = np.array([[1,2,3],[4,5,6]])
arr = np.add(arr,1)
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [37]:
# The above same operations can be achieve by using operator overloading.
# the below one is called operator overloading technique.

arr + 1

array([[3, 4, 5],
       [6, 7, 8]])

In [38]:
# squaring using operator overloading

arr**2

array([[ 4,  9, 16],
       [25, 36, 49]])

In [41]:
# If we want to perform column sum we use reduce function.
# It takes argument axis and if the value is 0 then it'll perform column sum

np.add.reduce(arr,axis=0)

array([ 7,  9, 11])

In [42]:
# If we want to perform row sum we can use axis = 1

np.add.reduce(arr,axis=1)

array([ 9, 18])