### Numpy library
Numpy library is very useful for mathematical manipulation , array manipulation , matrix manipulation

In [12]:
import numpy as np
np.array([1,2,3]) # array data structure exists inside numpy package
# converting list into array
type(np.array([1,2,3]))

numpy.ndarray

In [9]:
# upcasting

np.array([1,2,3.0]) # it will upcast all the elemnt of arry to floating point

array([1., 2., 3.])

In [13]:
# two dimentional array

np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
# converting to 6 dimentional array

np.array([1,2,3],ndmin = 6)

array([[[[[[1, 2, 3]]]]]])

In [19]:
# converting to complex number

np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [20]:
# upcasting to comple

np.array([1+8j,2,3])

array([1.+8.j, 2.+0.j, 3.+0.j])

In [28]:
x = np.array([(1,2),(3,4)], dtype = [('a','<i4'),('b','<i8')])

In [30]:
x['a']
x['b']

array([2, 4], dtype=int32)

In [40]:
# converting list into array

a = [1,2]

In [41]:
a = np.asarray(a)

In [42]:
np.asarray(a) is a

True

In [47]:
# issubclass is used to check the subclass of data structure

issubclass(np.matrix,np.ndarray) # is matrix a subclass of array

True

In [48]:
a = np.matrix([[1,2]])

In [50]:
np.asarray(a) is a

False

In [51]:
np.asanyarray(a) is a

True

In [53]:
a = [1,2]
np.asanyarray(a) # if dataset is not in form of any array then it'll try to convert it into array and if already present
# then it will not.

array([1, 2])

In [68]:
x = np.array([1,2])

In [69]:
id(x)

140539664834768

In [71]:
y = x
id(y) 

x[0] = 6

y
# this is a concept of shallow copy so if we want to modify any value of y then it will reflect for x too because both 
# x and y pointing to same memory location.

In [67]:
# Where as in case of deep copy if we copy one object variable to the another by using copy function and if we modify
# any one then it will not reflect into other because it occupy other mermory location.

x = [1,2,3]
z = np.copy(x)
x[0] = [5]
x

[[5], 2, 3]

### numpy.from function

In [75]:
np.fromfunction(lambda i,j : i == j,(3,3),dtype = int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [77]:
# iteratable object

iterable = (x * x for x in range(10))

In [79]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [81]:
np.fromstring('1,2',dtype=int,sep = ',') 

# converting numerical value to array

array([1, 2])

In [84]:
x1 = np.array([1,2,3])
x2 = np.array(['a','b','c'])
x3 = np.array([1.2,1.3,1.4])

x4 = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
x4

rec.array([(1, 'a', 1.2), (2, 'b', 1.3), (3, 'c', 1.4)],
          dtype=[('a', '<i8'), ('b', '<U1'), ('c', '<f8')])

In [87]:
# accessing element from above array

x4[1][1]

'b'

In [89]:
print('a series of number',np.arange(5,16))

# arange function can take floating point number

a series of number [ 5  6  7  8  9 10 11 12 13 14 15]


In [90]:
np.linspace(1,5,100)

# linspace basically generates number between two given numbers.It include upperbound as well.
# linspace accepts 3 arguments 1st : lower bound, 2nd : Upper bound,3rd : Numbers to be generated
# so linspace generates number with lower and upper bound with 100 numbers inbetween in given example

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [92]:
# generate matrix of random numbers

np.empty((3,5)) 

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [93]:
# generates matrix of zeros

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
# generate matrix of ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
# eye function is used to create identity matrix and it will alwapys create square matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
# logspace is similar to linspace only the major part is logspace try to generate logrithm number between given number

np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [112]:
# reshape function is basically reshape data set and it takes 2 argument 1st for row and 2nd for column

x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
# diag function gives diagonal elements of matrix

np.diag(x)

array([0, 4, 8])

In [114]:
np.diag(x,k=1)

array([1, 5])

In [115]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [119]:
# create 2D array with flatten input as diagonal

np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [122]:
# tri function basically creates a matrix where lower triangle elements woulb be 1 and upper triangle value would be 0

np.tri(5,5,2,dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [126]:
# random number generation(from uniform distribution)

np.random.rand(10,5) # 1st argument as row and 2nd argument as column

array([[0.7478209 , 0.57721575, 0.74166773, 0.41592881, 0.1084863 ],
       [0.11528568, 0.95615709, 0.79175802, 0.68545831, 0.06875541],
       [0.28370001, 0.94640372, 0.94894878, 0.48542129, 0.9975493 ],
       [0.55864225, 0.41500735, 0.1520242 , 0.79087769, 0.90758802],
       [0.87127483, 0.42013592, 0.09851258, 0.27385975, 0.0942928 ],
       [0.34575082, 0.69645365, 0.61338269, 0.00556672, 0.10829656],
       [0.96967419, 0.84833385, 0.83832569, 0.08336094, 0.19811781],
       [0.39840492, 0.34857633, 0.99312093, 0.05025242, 0.02666582],
       [0.67356787, 0.26267201, 0.35074442, 0.59380174, 0.72700024],
       [0.48151361, 0.25501337, 0.61283593, 0.10021729, 0.90116428]])

In [127]:
# from standard normal distribution

np.random.randn(2,2)

array([[-0.6608322 , -0.62061454],
       [ 1.42744064, -0.29988363]])

In [130]:
# randint generate random data between given numbers

np.random.randint(1,10,100)

array([5, 9, 1, 8, 4, 8, 7, 3, 9, 3, 4, 4, 3, 7, 4, 1, 1, 5, 2, 9, 2, 3,
       1, 4, 7, 4, 7, 8, 4, 4, 9, 8, 5, 5, 3, 3, 7, 1, 9, 1, 7, 1, 4, 2,
       6, 4, 7, 1, 8, 4, 5, 5, 3, 2, 5, 1, 8, 4, 9, 9, 3, 9, 6, 4, 8, 6,
       7, 7, 2, 5, 1, 7, 4, 9, 8, 6, 8, 4, 7, 7, 5, 2, 5, 1, 7, 7, 9, 3,
       5, 3, 3, 2, 3, 8, 5, 7, 3, 9, 6, 9])

In [9]:
# argmax returns the index of maximum element where as max return maximum element

from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(6,5)
b.argmax(axis = 0)

array([2, 3, 0, 0, 0])

In [13]:
mat = np.array([[22,33,44],[64,32,85],[33,85,26]])

In [16]:
mat[mat > 10]

# arrays are mutable element

array([22, 33, 44, 64, 32, 85, 33, 85, 26])

In [19]:
# matrix addition 

mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat3 = mat1 + mat2
mat3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
# in matrix multiplication if we use * sign then it will be index multiplication but if we use @ then it will
# perform matrix multiplication.

mat1 * mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
mat1 @ mat2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])