# Introduction to Numpy

In [1]:
# importing library

import numpy as np

In [2]:
# creating numpy array

lst = [[1,2,3],[4,5,6]]
twod_array = np.array(lst)
twod_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# checking array datatype

twod_array.dtype

dtype('int64')

In [6]:
# let's convert this to another dtype other than 64 bit

twod_array.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [7]:
# let's convert this to another data type say float

twod_array.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
# Checking dimensions

twod_array.ndim

2

In [9]:
# checking shape

twod_array.shape

(2, 3)

## Numpy array construction and indexing

In [11]:
# creating array of ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# with other data type by default it's in float

np.ones((3,3),dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
# creating array of zeros

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# to get help about any function

# way 1

np.ones?

# way 2

help(np.ones)

Signature: np.ones(shape, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
    

In [17]:
# adding values to np array

np.ones((3,3)) + 99

array([[100., 100., 100.],
       [100., 100., 100.],
       [100., 100., 100.]])

In [22]:
# creating empty array
# it will assign any random values while creating array

np.empty((2,3))

array([[1., 2., 3.],
       [4., 5., 6.]])