### Pytorch Library

In [55]:
# import pytorch library

import torch
import numpy as np

In [11]:
# creating empty array
# it basically create array with random numbers

a = torch.empty(6,3)
print(a)

tensor([[ 0.0000e+00, -3.6893e+19,  0.0000e+00],
        [-3.6893e+19,  2.5223e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [14]:
# creating rand arrays

a = torch.rand(4,3)
print(a)

tensor([[0.9357, 0.4601, 0.0195],
        [0.9641, 0.5555, 0.9601],
        [0.2265, 0.6279, 0.1191],
        [0.6178, 0.7214, 0.9466]])


In [15]:
# creating zeros matrix with datatype specified

a = torch.zeros(4,3,dtype = torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [20]:
# creating tensors with list

a = torch.tensor([7.1,8])
print(a)

tensor([7.1000, 8.0000])


In [21]:
# overwriting a value

a = a.new_ones(6,3,dtype = torch.double)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [26]:
# creating matrix with random number and acquiring shape from torch object using randn_like

a = torch.randn_like(a,dtype = torch.float)
print(a)

tensor([[ 0.3122,  0.2380,  1.1753],
        [-0.3858,  0.9215, -0.1780],
        [ 0.5977,  0.2612, -0.7625],
        [-0.8310,  1.1696,  0.3349],
        [-0.6224, -0.7436, -0.1002],
        [ 0.4978, -1.0044,  0.9828]])


In [27]:
# to check the size of object

a.size()

torch.Size([6, 3])

In [29]:
# Maths operation

b = torch.rand(6,3)
print(a + b)

tensor([[ 1.0918,  0.6621,  1.4203],
        [ 0.1121,  1.4387,  0.0219],
        [ 0.6129,  0.4747, -0.5200],
        [-0.1644,  1.8636,  0.7736],
        [-0.6221, -0.3173,  0.5999],
        [ 0.5917, -0.5212,  1.5851]])


In [30]:
# Another way to add

torch.add(a,b)

tensor([[ 1.0918,  0.6621,  1.4203],
        [ 0.1121,  1.4387,  0.0219],
        [ 0.6129,  0.4747, -0.5200],
        [-0.1644,  1.8636,  0.7736],
        [-0.6221, -0.3173,  0.5999],
        [ 0.5917, -0.5212,  1.5851]])

In [31]:
# we can store any value to object by using out parameter 

result = torch.rand(6,3)
torch.add(a,b,out = result)
print(result)

tensor([[ 1.0918,  0.6621,  1.4203],
        [ 0.1121,  1.4387,  0.0219],
        [ 0.6129,  0.4747, -0.5200],
        [-0.1644,  1.8636,  0.7736],
        [-0.6221, -0.3173,  0.5999],
        [ 0.5917, -0.5212,  1.5851]])


In [34]:
# adding a to b and we are using _ sigh called postfix which will assign addition value back to b

b.add_(a)
print(b)

tensor([[ 1.7161,  1.1381,  3.7710],
        [-0.6596,  3.2816, -0.3341],
        [ 1.8083,  0.9972, -2.0450],
        [-1.8264,  4.2028,  1.4434],
        [-1.8669, -1.8046,  0.3995],
        [ 1.5872, -2.5300,  3.5508]])


In [36]:
# indexing from object

print(a[:,1])

tensor([ 0.2380,  0.9215,  0.2612,  1.1696, -0.7436, -1.0044])


In [41]:
# reshaping the data using view

a = torch.randn(3,3)
print(a)
b = a.view(9)
print(b)

tensor([[-0.0506, -0.6714, -0.4807],
        [-1.1219,  1.0769, -0.8964],
        [ 0.7008, -0.6569, -0.2160]])
tensor([-0.0506, -0.6714, -0.4807, -1.1219,  1.0769, -0.8964,  0.7008, -0.6569,
        -0.2160])


In [49]:
# extracting values 
a = torch.randn(1)
print(a.item())

-1.4141666889190674


In [50]:
# creating tensor

a = torch.ones(4)
print(a)

tensor([1., 1., 1., 1.])


In [54]:
# converting tensor to numpy
y = a.numpy()
y

array([1., 1., 1., 1.], dtype=float32)

In [62]:
# converting torch object from numpy object

a = np.ones(4)
b = torch.from_numpy(a)
b

[1. 1. 1. 1.]


tensor([1., 1., 1., 1.], dtype=torch.float64)